$(document).ready(function(){
  $("#design").click(function(){
    $("#design").slideToggle();
    $("#design-info").slideToggle();
  });
  $("#design-info").click(function(){
    $("#design-info").slideToggle();
    $("#design").slideToggle();
  });
})